package com.kokabmedia.photoapp.api.account.data;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
/* 
 * The @Entity annotation from javax.persistence enables the JPA framework to manage 
 * the Category class as a JPA entity. The Category class is an entity and will be  
 * mapped to a database table with the name Category by Hibernate. 
 * 
 * The @Entity annotation will automatically with Hibernate, JPA and Spring auto 
 * configuration create a Category table in the database.
 */
@Entity
@Table(name = "AccountManager") // Sets the table name for this Entity
public class AccountManagementEntity implements Serializable {
	

	private static final long serialVersionUID = -510830257899234905L;

	/*
	 * The @Id annotation makes this field a primary key in the database table.
	 * 
	 * The @GeneratedValue annotation makes the Hibernate generate the primary key value.
	 * 
	 * The GenerationType.IDENTITY parameter indicates that the id will be generated by the
	 * hibernate.
	 * 
	 * Primary key will uniquely identify each row in a database table.
	 */
		@Id
		@GeneratedValue
		private Long id;
		
		// Column cannot be null and specify the string-valued column length is 50
		@Column(nullable=false, length=50) 
		private String usertName;
		
		@Column(nullable=false, length=50)
		private String firstName;

		@Column(nullable=false, length=50)
		private String lastName;
		
		// Has to be a unique value
		@Column(nullable=false, unique=true) 
		private String userId;


}
