package com.kokabmedia.photoapp.api.users.data;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
/* 
 * The @Entity annotation from javax.persistence enables the JPA framework to manage 
 * the Category class as a JPA entity. The User_Entity class is an entity and will be  
 * mapped to a database table with the name User_Entity by Hibernate. 
 * 
 * The @Entity annotation will automatically with Hibernate, JPA and Spring auto 
 * configuration create a User_Entity table in the database.
 */
@Entity
@Table(name = "users") // Name of the table for this Entity
public class UserEntity implements Serializable {

	private static final long serialVersionUID = -1790335188868936636L;

	/*
	 * The @Id annotation makes this field a primary key in the database table.
	 * 
	 * The @GeneratedValue annotation makes the Hibernate generate the primary key value.
	 * 
	 * The parameter indicates that the id will be generated by the
	 * hibernate.
	 * 
	 * Primary key will uniquely identify each row in a database table.
	 */
	@Id
	@GeneratedValue
	private Long id;
	
	// Cannot be null and the specified string-valued column length
	@Column(nullable=false, length=50) 
	private String firstName;

	@Column(nullable=false, length=50)
	private String lastName;

	@Column(nullable=false, length=120, unique=true)
	private String email;
		
	@Column(nullable=false, unique=true)
	private String userId;

	// Has to be uniqe
	@Column(nullable=false, unique=true)
	private String encryptedPassword;

	
	

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getEncryptedPassword() {
		return encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword;
	}
	
	

}
